# Use the official Node.js 18 image as the base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Expose port 3000
EXPOSE 3000

# Run the application
CMD ["npm", "run", "start:dev"]
